services:
  database:
    image: mysql:9.0
    container_name: symfonyBlog
    ports:
      - '3306:3306'
    volumes:
      - dev_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - TZ

  php:
    build:
      context: ./
      dockerfile: ./docker/phpfpm/Dockerfile
    env_file:
      - ./.env
    environment:
      - DATABASE_URL
      - TZ=$TZ
    # todo fix bin command to work without volumes here
    volumes:
      - .:/www

  nginx:
    build:
        context: ./
        dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '443:443'
    depends_on:
      - php

volumes:
  dev_mysql_data:
  var:
