services:
  database:
    image: mysql:8.2 # or mysql:8.2
    container_name: symfonyBlog
    ports:
      - '3306:3306'
    volumes:
      - dev_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD

  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.env
    environment:
      - DATABASE_URL
    # todo fix bin command to work without volumes here
    volumes:
      - .:/www

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/certs:/etc/nginx/certs
    ports:
      - '443:443'
    depends_on:
      - php

volumes:
  dev_mysql_data:
  var:
