parameters:
  thumbnail_dir: '%kernel.project_dir%/public/img/blog/thumbnails'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $targetDirectory: '%thumbnail_dir%' # Bind the parameter to the constructor argument

  App\Service\PagesService: ~ # Autowiring will automatically configure other dependencies

  App\Controller\BlogPageController: ~

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
