name: Deploy to Koyeb

on:
  workflow_dispatch:

jobs:
  deploy-to-koyeb:
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Deploy PHP-FPM to Koyeb
        run: |
          SERVICE_ID="YOUR_PHPFPM_SERVICE_ID"
          DEPLOYMENT=$(curl -s -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
            "https://app.koyeb.com/v1/services/$SERVICE_ID")
          
          SERVICE_DEFINITION=$(echo "$DEPLOYMENT" | jq '.service')
          
          UPDATED_SERVICE=$(echo "$SERVICE_DEFINITION" | jq --arg img "ghcr.io/jymarkb/symfony-blog-phpfpm:${{ env.TAG_NAME }}" '.container.image = $img')

          curl -X PATCH "https://app.koyeb.com/v1/services/$SERVICE_ID" \
            -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"service\":$UPDATED_SERVICE}"

      - name: Deploy Nginx to Koyeb
        run: |
          SERVICE_ID="YOUR_NGINX_SERVICE_ID"
          DEPLOYMENT=$(curl -s -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
            "https://app.koyeb.com/v1/services/$SERVICE_ID")
          
          SERVICE_DEFINITION=$(echo "$DEPLOYMENT" | jq '.service')

          UPDATED_SERVICE=$(echo "$SERVICE_DEFINITION" | jq --arg img "ghcr.io/jymarkb/symfony-blog-nginx:${{ env.TAG_NAME }}" '.container.image = $img')

          curl -X PATCH "https://app.koyeb.com/v1/services/$SERVICE_ID" \
            -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"service\":$UPDATED_SERVICE}"
