name: Production Build

on:
  push:
    tags:
      - "rc-*"  # Triggers only on tags that start with "rc-"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name for the tag
        run: |
          BRANCH_NAME=$(git branch -r --contains $GITHUB_SHA | grep 'origin/' | grep -v 'HEAD' | awk -F'/' '{print $NF}' | head -n 1)
          echo "Detected branch: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      
      - name: Check if tag is from production branch
        run: |
          if [[ "${{ env.BRANCH_NAME }}" != "production" ]]; then
            echo "Tag was not created from the production branch. Exiting."
            exit 1
          fi

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push PHP-FPM image
        run: |
          docker build -f docker/phpfpm/Dockerfile -t ghcr.io/jymarkb/symfony-blog-phpfpm:${{ env.TAG_NAME }} .
          docker push ghcr.io/jymarkb/symfony-blog-phpfpm:${{ env.TAG_NAME }}

      - name: Build and push Nginx image
        run: |
          docker build -f docker/nginx/Dockerfile -t ghcr.io/jymarkb/symfony-blog-nginx:${{ env.TAG_NAME }} .
          docker push ghcr.io/jymarkb/symfony-blog-nginx:${{ env.TAG_NAME }}

      - name: Trigger Deploy Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"production"}'
